<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="../Css/style.css">
    <title>E3J - Engenharia</title>
</head>
<body>
    <header><div id="header"></div></header>
    
    <main>
        <section class="section-01">
            <div class="text-01">
                <h1>INVESTINDO</h1>
                <h3>no presente,</h3>
                <h1>ECONOMIZANDO</h1>
                <h3>no futuro.</h3>
            </div>

            <img class="lampada" src="../components/img/lampada.png" alt="lampada ligada">    
        </section>

        <section class="section-02">
            <div class="text-02">
                <h2>Nossos</h2>
                <h2>Serviços</h2>
                <p>As melhores soluções para o seu negócio.</p>
                <button class="btn-orcamento"><strong>SAIBA MAIS</strong></button>
            </div>

            <div class="grade">
                <figure>
                    <img src="../components/img/Rectangle 12.png" alt="painel fotovoltaico">
                    <figcaption>SISTEMA FOTOVOLTAICO</figcaption>
                </figure>

                <figure>
                    <img src="../components/img/Rectangle 14.png" alt="Ilustração de tomada eletrica">
                    <figcaption>INSTALAÇÕES ELETRICAS</figcaption>
                </figure>

                <figure>
                    <img src="../components/img/Group 51.png" alt="Ilustração de reator">
                    <figcaption>ELETRÔNICA E AUTOMAÇÃO</figcaption>
                </figure>

                <figure>
                    <img src="../components/img/Group 52.png" alt="Ilustração de torre eletrica">
                    <figcaption>TELECOMUNICAÇÕES</figcaption>
                </figure>
                
                <figure>
                    <img src="../components/img/Group 53.png" alt="Histograma">
                    <figcaption>EFICIÊNCIA ENERGÉTICA</figcaption>
                </figure>
                
                <figure>
                    <img src="../components/img/Group 54.png" alt="Ilustração de Computador">
                    <figcaption>CURSOS E TREINAMENTOS</figcaption>
                </figure>  
            </div>
            
        </section>
    </main>
    
    <footer><div id="footer"></div></footer>

    <script src="../js/script.js"> </script>
</body>
</html>